#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li.d \$a7, SYS_${name}\n";
    print " syscall 0\n";
    print " jirl \$zero, \$ra, 0\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("getcpuid");
entry("read_sh_var");
entry("write_sh_var");
entry("chpri");
entry("sem_create");
entry("sem_p");
entry("sem_v");
entry("sem_free");
entry("shmgetat");
entry("shmrefcount");
entry("debug_v2p");
entry("mqget");
entry("msgsnd");
entry("msgrcv");
